import { useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch } from 'react-redux';
import { setPhoneNumber } from '../slices/phoneSlices';
import logo from '../asset/download.jpg'
import { useRouter } from 'next/router';

export default function Home() {
 const inputPhone = useRef();
 const router = useRouter();
 const dispatch = useDispatch();
 

 const handleLogin = () =>{
  dispatch(setPhoneNumber(inputPhone.current.value))
  router.push('/history')
 }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <header className='w-full border-b border-gray-200 p-4'>
      <Image
        src={'https://cdn.techinasia.com/data/images/Pb1HO9MRbbT0DZlbp2lMcrVV9uW4x6U681Oih3yM.jpeg'}
        alt="Picture of the logo"
        width={50}
        height={50}
      />
     </header>

     <main className='flex items-center justify-center h-screen w-full'>
        <div>
          <p className='text-center'> Personal Account for Business</p>
          <div className='flex items-center justify-center p-14 border-2 mt-5'>
                <input className='w-full text-gray-700 border py-2 pl-4 pr-12 mr-4' placeholder='Phone Number' ref={inputPhone}/>
                <button className='bg-blue-400 text-white font-bold py-2 px-16 rounded-xl' onClick={handleLogin}>Next</button>

          </div>
        </div>

     </main>
    </div>
  )
}
